site_name: MkLorum
site_url: https://example.com
nav:
  - Home: index.md
  - About: about.md

# Repository
repo_name: squidfunk/mkdocs-material
repo_url: https://github.com/squidfunk/mkdocs-material


# Configuration
theme:
  name: material